name: Download and Upload MP3

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'ダウンロードするURL'
        required: true
        type: string
      scrape_internal_links:
        description: '内部リンクをスクレイピングするか'
        required: true
        type: boolean
        default: false
      source_type:
        description: 'ダウンロード元の種類'
        required: true
        type: choice
        options:
          - auto_detect
          - soundcloud
          - bandcamp
          - archive
          - direct_link
        default: auto_detect

jobs:
  download_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          pip install yt-dlp requests beautifulsoup4
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: downloadsディレクトリの作成
        run: mkdir -p downloads

      - name: 音楽をダウンロード
        env:
          INPUT_URL: ${{ github.event.inputs.url }}
          INPUT_SCRAPE_LINKS: ${{ github.event.inputs.scrape_internal_links }}
          INPUT_SOURCE_TYPE: ${{ github.event.inputs.source_type }}
        run: |
          python downloader.py "$INPUT_URL" "$INPUT_SCRAPE_LINKS" "$INPUT_SOURCE_TYPE"

      - name: .gitattributes を設定（MP3を正しく扱う）
        run: |
          echo "*.mp3 filter=lfs diff=lfs binary" > downloads/.gitattributes
          echo "*.mp3 linguist-language=Audio" >> downloads/.gitattributes
          echo "*.mp3 mime-type=audio/mpeg" >> downloads/.gitattributes

      - name: MP3ファイルをGitHubに追加 & プッシュ
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add downloads/
          git commit -m "🎵 MP3ファイルを追加: $(date)" || exit 0
          git push origin HEAD:main
