name: Download Music Tracks

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'SoundCloud または Bandcamp の URL を入力'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          pip install yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: 音楽をダウンロード
        run: |
          python downloader.py "${{ github.event.inputs.url }}"

      - name: WAVファイルをGitHubにコミット
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add downloads/*.wav
          git commit -m "🎵 新しいWAVファイルを追加" || echo "No changes to commit"
          git push || echo "No changes to push"
