name: Download Music Tracks

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'ダウンロードするURLを入力'
        required: true
        type: string
      scrape_internal_links:
        description: '内部リンクをスクレイピングしますか？'
        required: true
        type: boolean
        default: false
      source_type:
        description: 'ダウンロード元の種類'
        required: true
        type: choice
        options:
          - auto_detect
          - soundcloud
          - bandcamp
          - archive
          - direct_link
        default: auto_detect

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          pip install yt-dlp requests beautifulsoup4
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: downloadsディレクトリの作成
        run: mkdir -p downloads

      - name: 音楽をダウンロード
        env:
          INPUT_URL: ${{ github.event.inputs.url }}
          INPUT_SCRAPE_LINKS: ${{ github.event.inputs.scrape_internal_links }}
          INPUT_SOURCE_TYPE: ${{ github.event.inputs.source_type }}
        run: |
          python downloader.py "$INPUT_URL" "$INPUT_SCRAPE_LINKS" "$INPUT_SOURCE_TYPE"

      - name: .gitattributesを更新
        run: |
          echo "*.mp3 mime-type=audio/mpeg" > downloads/.gitattributes
          git add downloads/.gitattributes
          git commit -m "🔄 `.gitattributes` を更新 (MP3 MIME type 設定)" || exit 0
          git push origin HEAD:main

      - name: ダウンロードされたファイルをGitHubに追加
        run: |
          git add downloads/
          git commit -m "🎵 新しい音楽ファイルを追加 [skip ci]" || exit 0
          git push origin HEAD:main
