name: Download Music Tracks

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'SoundCloud または Bandcamp の URL を入力'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完全な履歴を取得

      - name: Gitの設定
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          pip install yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: downloadsディレクトリの作成
        run: mkdir -p downloads

      - name: 音楽をダウンロード
        run: |
          python downloader.py "${{ github.event.inputs.url }}"

      - name: ファイルの存在確認とGitへの追加
        run: |
          if [ -n "$(ls -A downloads/*.mp3 2>/dev/null)" ]; then
            echo "MP3ファイルが見つかりました"
            git add downloads/*.mp3
          else
            echo "MP3ファイルが見つかりません"
            exit 1
          fi

      - name: 変更の確認とコミット
        run: |
          if git diff --cached --quiet; then
            echo "コミットする変更はありません"
          else
            echo "変更をコミットします"
            git commit -m "🎵 新しいMP3ファイルを追加 [skip ci]"
            git push origin HEAD:main
          fi
